// <auto-generated />
namespace ReviewsJoy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class up_down_votes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(up_down_votes));
        
        string IMigrationMetadata.Id
        {
            get { return "201511121030022_up_down_votes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
