// <auto-generated />
namespace ReviewsJoy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class placeId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(placeId));
        
        string IMigrationMetadata.Id
        {
            get { return "201509061619002_placeId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
